root: true

env:
  node: true
  mocha: true

plugins:
  - '@typescript-eslint'
  - prettier

extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

ignorePatterns:
  - '*.js'

rules: {}
